### ISSUE TITLE
Humidifier reports 0 temperature and humidity when offline

### ISSUE THREAD

**Issue by raulchen** [merdok/homebridge-miot#264]
I added my humidifier (deerma.humidifier.jsqs) to homebridge via this plugin.
The problem is, when the humidifier is offline, the plugin would still report 0°C temperature and 0% humidity to HomeKit.

I tried manually removing all “environment” stuff from the js file, the extra accessories in the following screenshot would be removed. 
![IMG_0088](https://user-images.githubusercontent.com/2883335/163831565-e0d16912-dd82-41e5-bec7-fc5ab5378d4e.jpeg)

But the “Current Relative Humidity” attribute was still there (see below screenshot).
![IMG_0090](https://user-images.githubusercontent.com/2883335/163831890-fed6b555-858a-4f5a-bae0-18fec22b372a.jpeg)

This is not a huge deal, but kind of annoying. Especially when you ask Siri, she would say the temperature ranges from 0 to something.  I only use the device in winter, so it’s offline most of time through the year. 

Is it possible to avoid reporting data when the device is offline (maybe show it as no response), or completely disable the temperature and humidity sensors?

Thank you.

**Comment by merdok** [comment]
Oh, you are right! Not sure how i missed that, but indeed the temperature sensor and relative humidity sensor are always set to active and do not change to inactive when the device goes offline. Will adjust that in the next update!

**Comment by merdok** [comment]
Should be fixed in 1.2.0

**Comment by raulchen** [comment]
@merdok Thanks for the quick fix. However, I’m still seeing the same issue after upgrading to 1.2.0.
Could you please take a look again? Following are the debug logs for my humidifier.

Initial logs when the device is connected. 
```
[5/21/2022, 10:44:32 AM] [miot] [Bedroom Humidifier] Got device configuration, initializing device with name: Bedroom Humidifier
[5/21/2022, 10:44:32 AM] [miot] [Bedroom Humidifier] Model known: deerma.humidifier.jsqs!
[5/21/2022, 10:44:32 AM] [miot] [Bedroom Humidifier] Initializing device!
[5/21/2022, 10:44:32 AM] [miot] [Bedroom Humidifier] Creating device instance by model: deerma.humidifier.jsqs!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Did not find device class! Trying to identify device from miot spec!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Found cached miot spec for device: deerma.humidifier.jsqs
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Parsing miot spec!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Using humidifier type and Humidifier description for device identification!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Got device type Humidifier from spec!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Found device type class at ../modules/humidifier/HumidifierDevice.js!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Using module class for device type Humidifier, indentified by miot spec! Not all features might work!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Initializing device services
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Device services: [
  "humidifier",
  "environment",
  "alarm",
  "indicator-light",
  "custom"
]
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Initializing device properties
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Device properties: [
  "humidifier:on",
  "humidifier:fault",
  "humidifier:fan-level",
  "humidifier:target-humidity",
  "environment:relative-humidity",
  "environment:temperature",
  "alarm:alarm",
  "indicator-light:on",
  "custom:water-shortage-fault",
  "custom:the-tank-filed",
  "custom:set-overwet-protect",
  "custom:other-sensors"
]
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Initializing device actions
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Device actions: [
  "custom:if-device-relative"
]
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Initializing device events
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Device events: [
  "custom:lack-of-water",
  "custom:bring-water-tank",
  "custom:overwet"
]
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Initial properties to monitor: [
  "humidifier:on",
  "humidifier:fault",
  "humidifier:fan-level",
  "humidifier:target-humidity",
  "custom:water-shortage-fault",
  "alarm:alarm",
  "indicator-light:on",
  "environment:temperature",
  "environment:relative-humidity"
]
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Successfully created a Humidifier device! It is a Unknown humidifier device.
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Found cached accessory for this device! Unregistering it first!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Initializing accessory!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Creating Humidifier accessory for device Bedroom Humidifier!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Found accessory class at ../modules/humidifier/HumidifierAccessory.js!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Accessory successfully initialized!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Final properties to monitor: [
  "humidifier:on",
  "humidifier:fault",
  "humidifier:fan-level",
  "humidifier:target-humidity",
  "custom:water-shortage-fault",
  "alarm:alarm",
  "indicator-light:on",
  "environment:temperature",
  "environment:relative-humidity"
]
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Registering 1 accessories!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Everything looks good! Initiating property polling!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] (Protocol) Call 192.168.2.33: miIO.info - {"timeout":5000,"retries":3} - {}
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Device found: deerma.humidifier.jsqs
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Setting up miot device!
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Doing basic setup
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Device firmware: 2.1.3
[5/21/2022, 10:44:33 AM] [miot] [Bedroom Humidifier] Doing MiCloud setup
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] Got device info from MiCloud: 
{
  "did": "455782265",
  "token": "…",
  "longitude": "0.0",
  "latitude": "0.0",
  "name": "…”,
  "pid": "0",
  "localip": "192.168.2.33",
  "mac": "B4:60:ED:5E:D7:8D",
  "ssid": "…",
  "bssid": "8C:DE:F9:E3:3C:2A",
  "parent_id": "",
  "parent_model": "",
  "show_mode": 1,
  "model": "deerma.humidifier.jsqs",
  "adminFlag": 1,
  "shareFlag": 0,
  "permitLevel": 16,
  "isOnline": true,
  "desc": "Device online ",
  "extra": {
    "isSetPincode": 0,
    "pincodeType": 0,
    "fw_version": "2.1.3",
    "needVerifyCode": 0,
    "isPasswordEncrypt": 0,
    "mcu_version": "0017"
  },
  "uid": …,
  "pd_id": 72559,
  "password": "",
  "p2p_id": "",
  "rssi": -37,
  "family_id": 0,
  "reset_flag": 0
}
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] Device setup finished! Miot device ready!
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] Connected to device: deerma.humidifier.jsqs
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] Doing initial property fetch.
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] (Protocol) Call 192.168.2.33: get_properties - [{"did":"455782265","siid":2,"piid":1},{"did":"455782265","siid":2,"piid":2},{"did":"455782265","siid":2,"piid":5},{"did":"455782265","siid":2,"piid":6},{"did":"455782265","siid":7,"piid":1},{"did":"455782265","siid":5,"piid":1},{"did":"455782265","siid":6,"piid":1},{"did":"455782265","siid":3,"piid":7},{"did":"455782265","siid":3,"piid":1}] - {}
[5/21/2022, 10:44:35 AM] [miot] [Bedroom Humidifier] Successfully saved device info!
```

Logs after the device disconnects.
```
5/21/2022, 10:54:04 AM] [miot] [Bedroom Humidifier] (Protocol) 192.168.2.33 <- Handshake timed out
[5/21/2022, 10:54:04 AM] [miot] [Bedroom Humidifier] (Protocol) 192.168.2.33 <- Reached maximum number of retries, giving up get_properties - [{"did":"455782265","siid":2,"piid":1},{"did":"455782265","siid":2,"piid":2},{"did":"455782265","siid":2,"piid":5},{"did":"455782265","siid":2,"piid":6},{"did":"455782265","siid":7,"piid":1},{"did":"455782265","siid":5,"piid":1},{"did":"455782265","siid":6,"piid":1},{"did":"455782265","siid":3,"piid":7},{"did":"455782265","siid":3,"piid":1}]
[5/21/2022, 10:54:04 AM] [miot] [Bedroom Humidifier] Poll failed 1 times!
[5/21/2022, 10:54:04 AM] [miot] [Bedroom Humidifier] Poll failed! Error: Error: Call to device timed out

```

**Comment by merdok** [comment]
Both the temperature and humidity sensor are now set to inactive when the device is not connected. Not sure how the Home app handles that...

**Comment by raulchen** [comment]
Is it possible to set the entire humidifier device as inactive, not just
the sensors?

**Comment by raulchen** [comment]
Is it possible to set the entire humidifier device as inactive, not just the sensors?

**Comment by raulchen** [comment]
If that’s not possible, maybe add an “enable” option to allow manually disable a device?

**Comment by merdok** [comment]
The device is also being already set as inactive when it is not connected. I am not sure why Siri would still pick them up even that they are inactive...
